name: sarthi-deploy
description: Easy to setup Docker based Ephemeral previews!
author: Tushar Gupta

branding:
  icon: check
  color: blue

runs:
  using: docker
  image: Dockerfile

inputs:
  sarthi_server_url:
    required: true
    description: 'URL of the deployed sarthi server'
  compose_file:
    description: 'Name of docker compose file in your project'
    default: docker-compose.yml
  sarthi_secret:
    required: true
    description: Secret text for authentication
  repo_token:
    default: ${{ github.token }}
    description: 'Github token of the repository (automatically created by Github)'

